package com.theodoremeras.dissertation.module_outcome_request;

import com.theodoremeras.dissertation.ec_application.EcApplicationEntity;
import com.theodoremeras.dissertation.ec_application.EcApplicationService;
import com.theodoremeras.dissertation.module.ModuleEntity;
import com.theodoremeras.dissertation.module.ModuleService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@RestController
public class ModuleOutcomeRequestController {

    private ModuleOutcomeRequestService moduleOutcomeRequestService;

    private EcApplicationService ecApplicationService;

    private ModuleService moduleService;

    private ModuleOutcomeRequestMapper moduleOutcomeRequestMapper;

    public ModuleOutcomeRequestController(
            ModuleOutcomeRequestService moduleOutcomeRequestService, EcApplicationService ecApplicationService,
            ModuleService moduleService, ModuleOutcomeRequestMapper moduleOutcomeRequestMapper
    ) {
        this.moduleOutcomeRequestService = moduleOutcomeRequestService;
        this.ecApplicationService = ecApplicationService;
        this.moduleService = moduleService;
        this.moduleOutcomeRequestMapper = moduleOutcomeRequestMapper;
    }

    @PostMapping(path = "/module-requests")
    public ResponseEntity<ModuleOutcomeRequestDto> createModuleOutcomeRequest(
            @RequestBody ModuleOutcomeRequestDto requestDto
    ) {
        // Id will be autogenerated
        requestDto.setId(null);

        ModuleOutcomeRequestEntity requestEntity = moduleOutcomeRequestMapper.mapFromDto(requestDto);

        // EC application and module must be specified when creating new module outcome request
        if (requestEntity.getEcApplication() == null || requestEntity.getModule() == null)
            return new ResponseEntity<>(HttpStatus.BAD_REQUEST);

        // Verify that the specified EC application exists
        Optional<EcApplicationEntity> ecApplication =
                ecApplicationService.findOneById(requestEntity.getEcApplication().getId());
        if (ecApplication.isPresent())
            requestEntity.setEcApplication(ecApplication.get());
        else
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);

        // Verify that the specified module exists
        Optional<ModuleEntity> module =
                moduleService.findOneByCode(requestEntity.getModule().getCode());
        if (module.isPresent())
            requestEntity.setModule(module.get());
        else
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);

        ModuleOutcomeRequestEntity savedRequestEntity = moduleOutcomeRequestService.save(requestEntity);
        return new ResponseEntity<>(moduleOutcomeRequestMapper.mapToDto(savedRequestEntity), HttpStatus.CREATED);
    }

    @GetMapping(path = "/module-requests")
    public List<ModuleOutcomeRequestDto> getAllModuleOutcomeRequests(
            @RequestParam(value = "ecApplicationId", required = false) Integer ecApplicationId
    ) {
        List<ModuleOutcomeRequestEntity> requestEntities =
                (ecApplicationId == null) ? moduleOutcomeRequestService.findAll() :
                moduleOutcomeRequestService.findAllByEcApplicationId(ecApplicationId);

        return requestEntities.stream()
                .map(moduleOutcomeRequestMapper::mapToDto)
                .collect(Collectors.toList());
    }

    @GetMapping(path = "/module-requests/{id}")
    public ResponseEntity<ModuleOutcomeRequestDto> getModuleOutcomeRequestById(@PathVariable("id") Integer id) {
        Optional<ModuleOutcomeRequestEntity> foundRequest = moduleOutcomeRequestService.findOneById(id);

        return foundRequest.map(requestEntity -> {
            ModuleOutcomeRequestDto requestDto = moduleOutcomeRequestMapper.mapToDto(requestEntity);
            return new ResponseEntity<>(requestDto, HttpStatus.OK);
        }).orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    @PatchMapping(path = "/module-requests/{id}")
    public ResponseEntity<ModuleOutcomeRequestDto> partialUpdateModuleOutcomeRequest(
            @PathVariable("id") Integer id, @RequestBody ModuleOutcomeRequestDto requestDto
    ) {
        if (!moduleOutcomeRequestService.exists(id))
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);

        requestDto.setId(id);
        ModuleOutcomeRequestEntity requestEntity = moduleOutcomeRequestMapper.mapFromDto(requestDto);
        ModuleOutcomeRequestEntity updatedRequestEntity = moduleOutcomeRequestService.partialUpdate(id, requestEntity);
        return new ResponseEntity<>(moduleOutcomeRequestMapper.mapToDto(updatedRequestEntity), HttpStatus.OK);
    }

    @DeleteMapping(path ="/module-requests/{id}")
    public ResponseEntity<String> deleteModuleOutcomeRequest(@PathVariable("id") Integer id) {
        moduleOutcomeRequestService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
