package com.theodoremeras.dissertation.department;


import jakarta.validation.ConstraintViolationException;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.*;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Collectors;

@RestController
public class DepartmentController {

    private DepartmentService departmentService;

    private DepartmentMapper departmentMapper;

    public DepartmentController(DepartmentService departmentService, DepartmentMapper departmentMapper) {
        this.departmentService = departmentService;
        this.departmentMapper = departmentMapper;
    }

    @PostMapping(path = "/departments")
    public ResponseEntity<DepartmentDto> createDepartment(@RequestBody @Valid DepartmentDto departmentDto) {
        // Id will be autogenerated
        departmentDto.setId(null);

        DepartmentEntity departmentEntity = departmentMapper.mapFromDto(departmentDto);
        DepartmentEntity savedDepartmentEntity = departmentService.save(departmentEntity);
        return new ResponseEntity<>(departmentMapper.mapToDto(savedDepartmentEntity), HttpStatus.CREATED);
    }

    @GetMapping(path = "/departments")
    public List<DepartmentDto> getAllDepartments() {
        List<DepartmentEntity> departmentEntities = departmentService.findAll();
        return departmentEntities.stream()
                .map(departmentMapper::mapToDto)
                .collect(Collectors.toList());
    }

    @GetMapping(path = "/departments/{id}")
    public ResponseEntity<DepartmentDto> getDepartmentById(@PathVariable("id") Integer id) {
        Optional<DepartmentEntity> foundDepartment = departmentService.findOneById(id);
        return foundDepartment.map(departmentEntity ->{
            DepartmentDto departmentDto = departmentMapper.mapToDto(departmentEntity);
            return new ResponseEntity<>(departmentDto, HttpStatus.OK);
        }).orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    @DeleteMapping(path = "/departments/{id}")
    public ResponseEntity<String> deleteDepartment(@PathVariable("id") Integer id) {
        departmentService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

    @ResponseStatus(HttpStatus.BAD_REQUEST)
    @ExceptionHandler(MethodArgumentNotValidException.class)
    public Map<String, String> handleValidationExceptions(
      MethodArgumentNotValidException ex) {
        Map<String, String> errors = new HashMap<>();
        ex.getBindingResult().getAllErrors().forEach((error) -> {
            String fieldName = ((FieldError) error).getField();
            String errorMessage = error.getDefaultMessage();
            errors.put(fieldName, errorMessage);
        });
        return errors;
    }

}
