package com.theodoremeras.dissertation.student_information;

import com.theodoremeras.dissertation.user.UserEntity;
import com.theodoremeras.dissertation.user.UserService;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.stream.Collectors;

@RestController
public class StudentInformationController {

    private StudentInformationService studentInformationService;

    private UserService userService;

    private StudentInformationMapper studentInformationMapper;

    public StudentInformationController(
            StudentInformationService studentInformationService,
            UserService userService, StudentInformationMapper studentInformationMapper
    ) {
        this.studentInformationService = studentInformationService;
        this.userService = userService;
        this.studentInformationMapper = studentInformationMapper;
    }

    @PostMapping(path = "/student-information")
    public ResponseEntity<StudentInformationDto> createStudentInformation(
            @RequestBody @Valid StudentInformationDto studentInformationDto
    ) {
        // Id will be autogenerated
        studentInformationDto.setId(null);

        StudentInformationEntity studentInformationEntity = studentInformationMapper.mapFromDto(studentInformationDto);

        // Verify that the specified student exists
        Optional<UserEntity> student = userService.findOneById(studentInformationEntity.getStudent().getId());
        if (student.isPresent())
            studentInformationEntity.setStudent(student.get());
        else
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);

        StudentInformationEntity savedStudentInformationEntity =
                studentInformationService.save(studentInformationEntity);
        
        return new ResponseEntity<>(
                studentInformationMapper.mapToDto(savedStudentInformationEntity),
                HttpStatus.CREATED
        );
    }

    @GetMapping(path = "/student-information")
    public List<StudentInformationDto> getAllStudentInformation(
            @RequestParam(value = "studentId", required = false) Integer studentId
    ) {
        //Determine whether to fetch all student information or only the that the provided student id
        List<StudentInformationEntity> studentInformationEntities;
        if (studentId == null)
                studentInformationEntities = studentInformationService.findAll();
        else {
            Optional<StudentInformationEntity> foundStudentInformation =
                    studentInformationService.findOneByStudentId(studentId);
            studentInformationEntities = foundStudentInformation
                    .map(studentInformationEntity -> new ArrayList<>(List.of(studentInformationEntity)))
                    .orElseGet(ArrayList::new);
        }

        return studentInformationEntities.stream()
                .map(studentInformationMapper::mapToDto)
                .collect(Collectors.toList());
    }

    @PatchMapping(path = "/student-information/{id}")
    public ResponseEntity<StudentInformationDto> partialUpdateStudentInformation(
            @PathVariable("id") Integer id, @RequestBody StudentInformationDto studentInformationDto
    ) {
        if (!studentInformationService.exists(id))
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);

        studentInformationDto.setId(id);
        StudentInformationEntity studentInformationEntity = studentInformationMapper.mapFromDto(studentInformationDto);
        StudentInformationEntity updatedStudentInformationEntity =
                studentInformationService.partialUpdate(id, studentInformationEntity);
        return new ResponseEntity<>(
                studentInformationMapper.mapToDto(updatedStudentInformationEntity),
                HttpStatus.OK
        );
    }

    @DeleteMapping(path = "/student-information/{id}")
    public ResponseEntity<String> deleteStudentInformation(@PathVariable("id") Integer id) {
        studentInformationService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

    @ResponseStatus(HttpStatus.BAD_REQUEST)
    @ExceptionHandler(MethodArgumentNotValidException.class)
    public Map<String, String> handleValidationExceptions(
      MethodArgumentNotValidException ex) {
        Map<String, String> errors = new HashMap<>();
        ex.getBindingResult().getAllErrors().forEach((error) -> {
            String fieldName = ((FieldError) error).getField();
            String errorMessage = error.getDefaultMessage();
            errors.put(fieldName, errorMessage);
        });
        return errors;
    }

}
