package com.theodoremeras.dissertation.module_decision;

import com.theodoremeras.dissertation.module_request.ModuleRequestEntity;
import com.theodoremeras.dissertation.module_request.ModuleRequestService;
import com.theodoremeras.dissertation.user.UserEntity;
import com.theodoremeras.dissertation.user.UserService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@RestController
public class ModuleDecisionController {

    private ModuleDecisionService moduleDecisionService;

    private ModuleRequestService moduleRequestService;

    private UserService userService;

    private ModuleDecisionMapper moduleDecisionMapper;

    public ModuleDecisionController(
            ModuleDecisionService moduleDecisionService, ModuleRequestService moduleRequestService,
            UserService userService, ModuleDecisionMapper moduleDecisionMapper
    ) {
        this.moduleDecisionService = moduleDecisionService;
        this.moduleRequestService = moduleRequestService;
        this.userService = userService;
        this.moduleDecisionMapper = moduleDecisionMapper;
    }

    @PostMapping(path = "/module-decisions")
    public ResponseEntity<ModuleDecisionDto> createModuleDecision(
            @RequestBody ModuleDecisionDto moduleDecisionDto
    ) {
        // Id will be autogenerated
        moduleDecisionDto.setId(null);

        ModuleDecisionEntity  moduleDecisionEntity = moduleDecisionMapper.mapFromDto(moduleDecisionDto);

        // The relevant module request and staff member who made the decision must be specified
        if (moduleDecisionEntity.getModuleRequest() == null || moduleDecisionEntity.getStaffMember() == null)
            return new ResponseEntity<>(HttpStatus.BAD_REQUEST);

        // Verify that the specified module request exists
        Optional<ModuleRequestEntity> moduleRequest =
                moduleRequestService.findOneById(moduleDecisionEntity.getModuleRequest().getId());
        if (moduleRequest.isPresent())
            moduleDecisionEntity.setModuleRequest(moduleRequest.get());
        else
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);


        // Verify that the specified staff member exists
        Optional<UserEntity> staff =
                userService.findOneById(moduleDecisionEntity.getStaffMember().getId());
        if (staff.isPresent())
            moduleDecisionEntity.setStaffMember(staff.get());
        else
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);

        ModuleDecisionEntity savedModuleDecisionEntity = moduleDecisionService.save(moduleDecisionEntity);
        System.out.println(savedModuleDecisionEntity);
        return new ResponseEntity<>(moduleDecisionMapper.mapToDto(savedModuleDecisionEntity), HttpStatus.CREATED);
    }

    @GetMapping(path = "/module-decisions")
    public List<ModuleDecisionDto> getAllModuleDecisions(
            @RequestParam(value = "moduleRequestId", required = false) Integer moduleRequestId
    ) {
        // Determine whether to fetch all requests or only those matching the provided module request id
        List<ModuleDecisionEntity>  moduleDecisionEntities =
                (moduleRequestId == null) ? moduleDecisionService.findAll() :
                        moduleDecisionService.findAllByModuleRequestId(moduleRequestId);

        return moduleDecisionEntities.stream()
                .map(moduleDecisionMapper::mapToDto)
                .collect(Collectors.toList());
    }

    @GetMapping(path = "/module-decisions/{id}")
    public ResponseEntity<ModuleDecisionDto> getModuleDecisionById(@PathVariable("id") Integer id) {
        Optional<ModuleDecisionEntity> foundEntity = moduleDecisionService.findOneById(id);
        System.out.println(foundEntity);

        return foundEntity.map(moduleDecisionEntity -> {
            ModuleDecisionDto moduleDecisionDto = moduleDecisionMapper.mapToDto(moduleDecisionEntity);
            return new ResponseEntity<>(moduleDecisionDto, HttpStatus.OK);
        }).orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    @DeleteMapping(path = "/module-decisions/{id}")
    public ResponseEntity<String> deleteModuleDecision(@PathVariable("id") Integer id) {
        moduleDecisionService.delete(id);
        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

}
