spring:
  application:
    name: dissertation
  datasource:
    url: jdbc:postgresql://localhost:5432/ecf_db
    username: postgres
    password: bacon123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB
