spring:
  application:
    name: dissertation
  datasource:
    # Default PostgreSQL port is 5432; if it's not the case for your machine
    # change the port accordingly in the below url
    url: jdbc:postgresql://localhost:5432/enter_your_database_name_here
    username: enter_your_username_here
    password: enter_your_user_password_here
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB
