spring:
  application:
    name: dissertation
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: bacon123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB
